### ISSUE TITLE
Page candidature

### ISSUE THREAD

**Issue by MathildeBras** [eig-ne/eig.ne#12]
...elle est très belle.

Quelques feedbacks:
- Remplacer titre section "Candidater au programme EIG" par "Devenir EIG"

- Je m'interroge sur la correspondance entre texte et parcours utilisateurs.
Il est dit "télécharger" avec de candidater" et en fait les documents clés sont en dessous du bouton télécharger.

**Comment by AntoineAugusti** [comment]
> Je m'interroge sur la correspondance entre texte et parcours utilisateurs.
Il est dit "télécharger" avec de candidater" et en fait les documents clés sont en dessous du bouton télécharger.

J'avais mis les documents en dessous car ils sont pour moi facultatifs. Si tu es un entrepreneur, tu peux t'en sortir en remplissant le formulaire.

Les documents sont pour les prudents, qui veulent préparer leur dossier avant. Peut-être que je me trompe ! On peut faire des ajustements.
