### ISSUE TITLE
Page contact - UX

### ISSUE THREAD

**Issue by MathildeBras** [eig-ne/eig.ne#13]
Quelques retours :
1) redirection page candidature EIG
- le premier bloc sur la candidature est un peu confusant, je changerais l'angle en termes de rédaction en écrivant à quoi sert ce formulaire de contact, pour ensuite dire, si vous souhaitez devenir EIG, vous pouvez vous rendre sur (....page de candidature)
- en corollaire enlever le remplissage vert

2)
Une fois le formulaire rempli, on arrive sur le truc formspree, mais ce serait pas ensuite de revenir sur la page du site ?

**Comment by AntoineAugusti** [comment]
La redirection vers le site en retour n'est possible que pour les plans payants sur Formspree malheureusement : https://help.formspree.io/hc/en-us/articles/360012378333--Thank-You-redirect
