### ISSUE TITLE
Bandeau d'accueil - Modifier texte + emplacement

### ISSUE THREAD

**Issue by MathildeBras** [eig-ne/eig.ne#9]
- J'ai compris ce qui me genait graphiquement : en fait le haut de l'image montre le ciel, et cela donne une impression de biais, il y a moyen de corriger ?
- Centrer le texte sur l'image ?
- Le bandeau transparent : le mettre sur toute la longueur de l'image
- "EIG.ne - le numérique au service du citoyen" --> Entrepreneur d'intérêt général Niger - Le numérique par les nigériens pour les nigériens.

**Comment by AntoineAugusti** [comment]
Avant
![image](https://user-images.githubusercontent.com/295709/77918386-d2ae6b00-7269-11ea-8208-85edff5ec9de.png)
Après
![image](https://user-images.githubusercontent.com/295709/77918443-e6f26800-7269-11ea-9db7-a4bc18fcc719.png)
